<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Fadee Kannah - Homepage</title>
<?php include("inc/meta.inc"); ?>
<?php include("inc/styles.inc"); ?>
<?php include("inc/scripts.inc"); ?>
</head>
<body>
<div id="templatemo_wrapper">    
<?php include("inc/header.inc"); ?>

<div id="templatemo_middle">
   	<div class="middle_box">
        	<h2>Another New Page</h2>
            <img src="images/paper.png" alt="Image 01" class="float_l" />
            <p>Added <a href="arduino.phtml">arduino</a> page for some of my arduino projects.</p>
        	<a href="news-3.phtml" class="mb_more">More</a>
        </div>
        <div class="middle_box">
        	<h2>Old Project Done!</h2>
            <img src="images/screen.png" alt="Image 02" class="float_l" />
            <p>The Mouse Picker is ready for use!.</p>
        	<a href="news-2.phtml" class="mb_more">More</a>
        </div>
        
        <div id="slider-wrapper">
            <div id="slider" class="nivoSlider">
                <a href="http://www.mrkannah.com/" title="My Website"><img src="images/slider/01.jpg" alt="Fadee Kannah" /></a>
                <a href="http://healthescortservices.com/" title="CHES"><img src="images/slider/02.jpg" alt="CHES"  /></a>
                <a href="http://brianallencarpet.com/" title="Brain Allen Carpet Cleaning"><img src="images/slider/03.jpg" alt="Brain Allen Carpet Cleaning" /></a>
                <a href="http://www.alaakana.com/" title="Alaa Kana"><img src="images/slider/04.jpg" alt="Alaa Kana" /></a>
                <a href="samples/mechatronics/index.php" title="Mechatronics"><img src="images/slider/05.jpg" alt="Mechatronics" /></a>
                <a href="http://casuclub.tk/" title="CASU Club"><img src="images/slider/06.jpg" alt="CASU Club" /></a>
                <a href="samples/projectx/" title="Project X"><img src="images/slider/07.jpg" alt="Project X" /></a>
                <a href="https://chrome.google.com/webstore/detail/youtube-redirector/fnlklbjlpkkdnelohembgpdahpfpfcbp" title="YouTube Redirector"><img src="images/slider/08.jpg" alt="YouTube Redirector" /></a>
                <a href="news-2.phtml" title="Mouse Picker"><img src="images/slider/09.jpg" alt="Mouse Picker" /></a>
            </div>
        </div>
            <div class="cleaner"></div>
        </div>
<div id="templatemo_main_wrapper"> <span class="top"></span><span class="bottom"></span>
        <div id="templatemo_main">        
    	<h3>Welcome</h3> 
        <p>I am Fadee Kannah, a third year (junior) at San Diego State University who is majoring in computer engineering and minoring in computer science. I chose computer engineering as my major because of my passion towards technology and computers. I realized that my future will be based on this passion since I was twelve when I held a computer mouse for the first time.</p>
        <p>I am currently the IT assistant for EOP (Educational Opportunity Programs and Ethnic Affairs) and College of Education at San Diego State University. I help facuilty and students who are experincing technological difficulties. I also Manage and maintain the department inventory of over $100k worth of hardware and software equipment. And I developed, and currently maintain, department website while meeting Federal ADA Compliances.</p>
        <p>I am also the president and founder of <a href="http://casuclub.tk/">Chaldean American Student Union (CASU)</a>. CASU is an organization that provides assistance and support to its members while introducing and promoting Chaldean and Middle Eastern cultures.</p>
        <p>Also, I am currently the webmaster for the <a href="http://ieee.sdsu.edu/">Institute of Electrical and Electronics Engineers (IEEE)</a> at San Diego State University.</p>
        <p>In addition to that, I am a the president and one of the founders of  <a href="http://hitechedventures.org/">HiTech EdVentures</a>. HTEV is a new student organization and a business where  students get contracted to work on projects supplied by the faculty of San Diego State University and/or industry.</p>
        <p>Finally, I am a part of the  <a href="http://eop.sdsu.edu/">Office of Educational Opportunity Programs and Ethnic Affairs</a>, <a href="http://www.sci.sdsu.edu/casa/lsamp/">The Louis Stokes Alliance for Minority Participation</a> and <a href="http://mep.sdsu.edu/">Mesa Engineering Progam</a>.</p>
        <p>Those are just a few of the things that I do on my free time. I always have at least a couple projects in progress at the same time. Such as developing software, designing websites, incorporating new things to old projects, and messing around with different software.</p>

        <div class="cleaner"></div>
        </div>
    </div>    

<?php include("inc/footer.inc"); ?>

</body>
</html>