<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Fadee Kannah - News</title>
<?php include("inc/meta.inc"); ?>
<?php include("inc/styles.inc"); ?>
<?php include("inc/scripts.inc"); ?>
</head>
<body>

<div id="templatemo_wrapper">
<?php include("inc/header.inc"); ?>
    <div id="templatemo_main_wrapper"> <span class="top"></span><span class="bottom"></span>
    	<div id="templatemo_main">
           <h2>Another New Page</h2>
           <p>This page was need due to the lack of a place to put my arduino projects on.</p>
           <p>The page is called <a href="arduino.phtml">Arduino Projects</a> because it has my arduino projects. Some of those The page will only include a description of the project and a video. The information on how to do the projects yourself is included in the video description.</p>
           <p>Keep checking the page for new projects.</p>
         	<div class="cleaner"></div>
        </div> <!-- end of main -->
    </div> <!-- end of main wrapper -->
    
<?php include("inc/footer.inc"); ?>

</body>
</html>