<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Fadee Kannah - Portfolio</title>
<?php include("inc/meta.inc"); ?>
<?php include("inc/styles.inc"); ?>
<?php include("inc/scripts.inc"); ?>
</head>
<body>

<div id="templatemo_wrapper">
<?php include("inc/header.inc"); ?>
    <div id="templatemo_main_wrapper"> <span class="top"></span><span class="bottom"></span>
    	<div id="templatemo_main">
        	
            <h2>Portfolio</h2>
            
        	<div class="middle_box">
        	<h2>Volunteering</h2>
            <img src="images/security.png" alt="Image 01" class="float_l" />
            <p>Small information about the volunteering that I did.</p>
        	<a href="volunteer.phtml" class="mb_more">More</a>
        	</div>
            <div class="middle_box">
        	<h2>Awards</h2>
            <img src="images/trophy.png" alt="Image 01" class="float_l" />
            <p>A summary of most of the awards that I have recieved.</p>
        	<a href="awards.phtml" class="mb_more">More</a>
        	</div>
            <div class="middle_box">
        	<h2>Resume</h2>
            <img src="images/paper.png" alt="Image 01" class="float_l" />
            <p>Copy of my resume.</p>
        	<a href="resume.phtml" class="mb_more">More</a>
        	</div>
        	<div class="cleaner h10"></div>
        </div> <!-- end of main -->
    </div> <!-- end of main wrapper -->
    
<?php include("inc/footer.inc"); ?>
</body>
</html>