<div id="templatemo_menu" class="ddsmoothmenu">
  <ul>
    <li>
      <a href="index.php">Home<span>Start here</span></a>
    </li>
    <li>
      <a href="about.php">About<span>Who we are</span></a>
    </li>
    <li>
      <a href="gallery.php">Gallery<span>What we have done</span></a>
    </li>
    <li>
      <a href="staff.php">Staff<span>Our team</span></a>
    </li>
    <li>
      <a href="contact.php">Contact<span>Get to us</span></a>
    </li>
    <li>
      <a href="login.php">Membership mangement<span>Admin page</span></a>
    </li>
  </ul>
  <br style="clear: left" />
</div>
<!-- END of menu -->
