	<div id="templatemo_menu" class="ddsmoothmenu">
        <ul>
            <li><a href="index.php">Home<span>Start here</span></a></li>
            <li><a href="about.phtml">About<span>Who we are</span></a></li>
            <li><a href="gallery.phtml">Gallery<span>What we have done</span></a></li>
			<li><a href="staff.phtml">Staff<span>Our team</span></a></li>
			<li><a href="contact.php">Contact<span>Get to us</span></a></li>
			<li><a href="login.php">Membership mangement<span>Admin page</span></a></li>
        </ul>
        <br style="clear: left" />
    </div> <!-- END of menu -->