<div id="templatemo_menu" class="ddsmoothmenu">
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="bio.php">Biography</a></li>
    <li>
      <a href="portfolio.php">Portfolio</a>
      <ul>
        <span class="top"></span
        ><span class="bottom"></span>
        <li><a href="volunteer.php">Volunteering</a></li>
        <li><a href="awards.php">Awards</a></li>
        <li><a href="resume.php">Resume</a></li>
      </ul>
    </li>
    <li>
      <a href="work.php">Work Samples</a>
      <ul>
        <span class="top"></span
        ><span class="bottom"></span>
        <li><a href="sites.php">Websites</a></li>
        <li><a href="tools.php">WebTools</a></li>
        <li><a href="arduino.php">Arduino</a></li>
        <li><a href="graphics.php">Graphics</a></li>
        <li><a href="others.php">Others</a></li>
      </ul>
    </li>
    <!--
              <li><a href="http://blog.mrkannah.com/">Blog</a></li>
			  -->
    <li><a href="contact.php">Contact</a></li>
  </ul>
  <br style="clear: left" />
</div>
