        <div id="templatemo_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="index.phtml">Home</a></li>
                <li><a href="bio.phtml">Biography</a></li>				
                <li><a href="portfolio.phtml">Portfolio</a>
                    <ul>
                    	<span class="top"></span><span class="bottom"></span>               
                        <li><a href="volunteer.phtml">Volunteering</a></li>
                        <li><a href="awards.phtml">Awards</a></li>
                        <li><a href="resume.phtml">Resume</a></li>
                   </ul>
              </li>
              <li><a href="work.phtml">Work Samples</a>
			  	   <ul>
                    	<span class="top"></span><span class="bottom"></span>               
                        <li><a href="sites.phtml">Websites</a></li>
						<li><a href="tools.phtml">WebTools</a></li>
						<li><a href="arduino.phtml">Arduino</a></li>
                        <li><a href="graphics.phtml">Graphics</a></li>
                        <li><a href="others.phtml">Others</a></li>
                   </ul>
			  </li>
			  <!--
              <li><a href="http://blog.mrkannah.com/">Blog</a></li>
			  -->
              <li><a href="contact.phtml">Contact</a></li>
            </ul>
            <br style="clear: left" />
        </div>